config/routes.rb
Rails.application.routes.draw do
  resources :races, only: [:index, :show]

  root 'races#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/race.rb
# == Schema Information
#
# Table name: races
#
#  id         :bigint           not null, primary key
#  no         :string(255)
#  year       :integer
#  kind       :string(255)
#  direction  :string(255)
#  weather    :string(255)
#  condition  :string(255)
#  distance   :integer
#  prize      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Race < ApplicationRecord
  has_many :tanfuku_odds
  has_many :umaren_odds
  has_many :umatan_odds
  has_many :wide_odds
end

app/models/race_result.rb
# == Schema Information
#
# Table name: race_results
#
#  id         :bigint           not null, primary key
#  race_id    :bigint
#  umaban     :integer
#  result     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RaceResult < ApplicationRecord
  belongs_to :race
end

app/models/tanfuku_odds.rb
# == Schema Information
#
# Table name: tanfuku_odds
#
#  id         :bigint           not null, primary key
#  race_id    :bigint
#  umaban     :integer
#  tan        :float(24)
#  fuku       :float(24)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TanfukuOdds < ApplicationRecord
  belongs_to :race
end

app/models/this_week_race.rb
# == Schema Information
#
# Table name: wide_odds
#
#  id         :bigint           not null, primary key
#  race_id    :bigint
#  first      :integer
#  second     :integer
#  odds       :float(24)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ThisWeekRace < ApplicationRecord
end

app/models/umaren_odds.rb
class UmarenOdds < ApplicationRecord
  belongs_to :race
end

app/models/umatan_odds.rb
# == Schema Information
#
# Table name: umatan_odds
#
#  id         :bigint           not null, primary key
#  race_id    :bigint
#  first      :integer
#  second     :integer
#  odds       :float(24)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UmatanOdds < ApplicationRecord
  belongs_to :race
end

app/models/wide_odds.rb
# == Schema Information
#
# Table name: wide_odds
#
#  id         :bigint           not null, primary key
#  race_id    :bigint
#  first      :integer
#  second     :integer
#  odds       :float(24)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class WideOdds < ApplicationRecord
  belongs_to :race
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = ThisWeekRace.all
    @dates = @races.pluck(:date).uniq
    @holds = @races.pluck(:hold).uniq
  end

  def show
    @race = ThisWeekRace.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EKS -EviKeibaSystem-</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-area race">
      <%= yield %>
    </div>
  </body>
</html>

app/views/races/index.html.erb
<% @dates.each do |date| %>
  <div class="date-area">
    <%= date %>
  </div>
  <div class="race-area row">
    <% today_races = @races.where(date: date) %>
    <% today_holds = today_races.pluck(:hold).uniq %>
    <% panel_size = 12 / today_holds.size %>

    <% today_holds.each do |hold| %>
      <div class="col-sm-<%= panel_size %>">
        <div class="card">
          <div class="card-header">
            <%= hold %>
          </div>
          <div class="card-body">
            <table>
              <tr>
                <th></th>
                <th>レース名</th>
                <th>種別</th>
                <th>距離</th>
              </tr>
              <% hold_races = today_races.where(hold: hold) %>
              <% hold_races.each do |hold_race| %>
                <tr>
                  <td><%= hold_race.no %>R</td>
                  <td><%= link_to hold_race.name, race_path(hold_race)  %></td>
                  <td><%= hold_race.info %></td>
                  <td><%= hold_race.distance %></td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <br>
<% end %>

app/views/races/show.html.erb
<%= @race.name %>